
server:
  port: 6090
  disableTLS: true
  enableTelemetry: true
  telemetryCollector: localhost:4317
  rateLimits:
    globalReqRateLimitPerSec: 100
    serviceConcurrentRequestAllowance: 10
    store:
      type: redis
      connection: redis:6379
