apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  url: http://mimir:9009/prometheus
  isDefault: true
  access: proxy
  editable: true
  uid: prometheusdatasource
- name: Tempo
  type: tempo
  url: http://tempo:3200/
  access: proxy
  editable: true

